language: node_js
node_js:
  - "8.11"

before_deploy:
  - wget https://broth.itch.ovh/butler/linux-amd64/LATEST/.zip -O /tmp/butler.zip
  - unzip /tmp/butler.zip -d /tmp
  - export PATH=$PATH:/tmp/

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: release
